[package]
name = "mdbook-typst"
version = "0.1.0"
edition = "2021"
authors = ["duskmoon (Campbell He) <kp.campbell.he@duskmoon314.com>"]
description = "mdbook preprocessor to add typst support"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"
clap = { version = "4.5.4", features = ["derive"] }
comemo = "0.4.0"
flate2 = "1.0.28"
fontdb = "0.16.2"
mdbook = "0.4.37"
pulldown-cmark = { git = "https://github.com/pulldown-cmark/pulldown-cmark.git", branch = "branch_0.11" }
reqwest = { version = "0.12.3", features = ["blocking"] }
semver = "1.0.22"
serde_json = "1.0.115"
tar = "0.4.40"
time = { version = "0.3.34", features = ["local-offset"] }
typst = { version = "0.11.0", git = "https://github.com/typst/typst.git", tag = "v0.11.0" }
typst-svg = { version = "0.11.0", git = "https://github.com/typst/typst.git", tag = "v0.11.0" }
